# Generated by Django 4.0.2 on 2022-02-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewproduct',
            old_name='prduct',
            new_name='product',
        ),
    ]
