# Generated by Django 4.0.2 on 2022-02-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewproduct',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='reviewproduct',
            table='review_product',
        ),
    ]
